/* Auto-generated — do not edit directly. Edit lang/*.json and titles/*.json instead. */

window.LANG_DATA = {};
window.LANG_DATA["en"] = {"distance.label": "Miles to Drive", "highway.mix": "Highway Mix", "highway.slider": "Hwy", "city.slider": "City", "result.label": "Estimated Trip Cost", "numbers.heading": "Your Numbers", "eff.hwy": "Highway", "eff.city": "City", "fuel.price": "Fuel Price", "region.label": "Region", "metric.label": "Fuel Metric", "footer.tagline": "safe travels, friend 🤙", "aria.settings": "Region and fuel metric settings", "aria.distance": "Number of miles to drive", "aria.highway": "Highway driving percentage", "aria.result": "Estimated trip cost result"};
window.LANG_DATA["fr"] = {"distance.label": "Distance", "highway.mix": "Répartition", "highway.slider": "Auto", "city.slider": "Ville", "result.label": "Coût estimé du trajet", "numbers.heading": "Vos données", "eff.hwy": "Autoroute", "eff.city": "Ville", "fuel.price": "Prix du carburant", "region.label": "Région", "metric.label": "Consommation", "footer.tagline": "bonne route 🤙", "aria.settings": "Paramètres de région et de consommation", "aria.distance": "Nombre de kilomètres à parcourir", "aria.highway": "Pourcentage de conduite sur autoroute", "aria.result": "Résultat du coût estimé du trajet"};
window.LANG_DATA["pt"] = {"distance.label": "Distância", "highway.mix": "Distribuição", "highway.slider": "Auto", "city.slider": "Cidade", "result.label": "Custo estimado da viagem", "numbers.heading": "Os seus dados", "eff.hwy": "Auto-estrada", "eff.city": "Cidade", "fuel.price": "Preço do combustível", "region.label": "Região", "metric.label": "Métrica de consumo", "footer.tagline": "boa viagem 🤙", "aria.settings": "Definições de região e métrica de combustível", "aria.distance": "Número de quilómetros a percorrer", "aria.highway": "Percentagem de condução em auto-estrada", "aria.result": "Resultado do custo estimado da viagem"};
window.LANG_DATA["zh"] = {"distance.label": "行驶里程", "highway.mix": "高速 / 城市", "highway.slider": "高速", "city.slider": "城市", "result.label": "预估费用", "numbers.heading": "您的参数", "eff.hwy": "高速公路", "eff.city": "城市道路", "fuel.price": "油价", "region.label": "地区", "metric.label": "油耗指标", "footer.tagline": "一路顺风 🤙", "aria.settings": "地区和油耗指标设置", "aria.distance": "行驶公里数", "aria.highway": "高速公路驾驶百分比", "aria.result": "预估行程费用结果"};

window.TITLES_DATA = {};
window.TITLES_DATA["en"] = [{"plain": "How Far", "em": "… and at what cost?", "subtitle": "Know the damage before you leave the driveway."}];
window.TITLES_DATA["fr"] = [{"plain": "C'est combien,", "em": " ce trajet ?", "subtitle": "Calculez le coût avant de prendre la route."}];
window.TITLES_DATA["pt"] = [{"plain": "Quanto vai custar", "em": " a viagem?", "subtitle": "Calcule o custo antes de sair de casa."}];
window.TITLES_DATA["zh"] = [{"plain": "这趟要花多少", "em": "领油钉？", "subtitle": "出发前先算清油费，心里有数。"}];
